# Servidor principal (Escucha en el puerto 80 estándar)
server {
    listen 80;
    server_name localhost;

    # 1. FRONTEND PÚBLICO (React)
    location / {
        proxy_pass http://front-publico:5137;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # 2. BACKEND (Spring Boot)
    # Tus peticiones desde React se harán a http://localhost/api/...
    location /api/ {
        proxy_pass http://backend:8080; # Sin barra final: conserva el prefijo /api/ que Spring Boot espera
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
        # Seguridad extra para la API
        proxy_hide_header X-Powered-By;
    }

    # 3. FRONTEND DE ADMINISTRACIÓN (React - Muy Capado por IP)
    location /admin/ {
        # 🔒 RESTRICCIÓN POR IP 
        # Para desarrollo local, permitimos todo. En producción, cambia 'allow all' por tu IP:
        allow all; 
        # Ejemplo en producción:
        # allow 185.23.45.112; # Tu IP pública real
        # deny all;            # Bloquea al resto del mundo

        proxy_pass http://front-admin:5137/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # 4. PEQUEÑO APARTADO DE ESTADÍSTICAS (Python Flask)
    # Tus endpoints como '/grafico/kpis' se llamarán desde el front-admin a http://localhost/grafico/...
    location /grafico/ {
        # 🔒 Protegemos las estadísticas con la misma regla de IP que el Admin
        allow all;
        # Ejemplo en producción:
        # allow 185.23.45.112;
        # deny all;

        proxy_pass http://python-stats:5000/grafico/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}