spring.config.import=optional:file:.env[.properties]

# --- CONFIGURACIÓN DE LA BASE DE DATOS ---
spring.datasource.url=jdbc:mysql://localhost:3306/jerezsur_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=toor
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- CONFIGURACIÓN DE JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Importante para que Hibernate no intente crear tablas que ya existen o de forma errónea
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# --- CONFIGURACIÓN DE SEGURIDAD OAUTH2 ---
# Google
spring.security.oauth2.client.registration.google.client-id=453262356994-ppst0cutlu3lpc0c1pvojqrjbegorngn.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

# Apple
#spring.security.oauth2.client.registration.apple.client-id=${APPLE_CLIENT_ID}
#spring.security.oauth2.client.registration.apple.client-secret=${APPLE_CLIENT_SECRET}
#spring.security.oauth2.client.registration.facebook.scope=email,public_profile

# Facebook
#spring.security.oauth2.client.registration.facebook.client-id=${FACEBOOK_CLIENT_ID}
#spring.security.oauth2.client.registration.facebook.client-secret=${FACEBOOK_CLIENT_SECRET}
#spring.security.oauth2.client.registration.facebook.scope=email,public_profile

# --- CONFIGURACIÓN DE LOGS ---
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG

# --- LÍMITES DE SUBIDA (Para las fotos de inmuebles e imágenes de perfil) ---
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# JWT
jwt.secret=dPiCNUsL3ylKz5JR2M8bVFxeZgAnfwXQkqcWGmHIptOa9v4hTjDSY16oBu70Er
jwt.expiration=86400000